### Jobs API Tests
@baseUrl = http://localhost:4000
@contentType = application/json
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoi0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC-0YAiLCJpYXQiOjE3NTk3NzQyOTQsImV4cCI6MTc1OTc3Nzg5NH0.uEtj5iYmrq_GgSksrqpJbwwS3NjfGnRor8cMjWou7UE

### 1. Create application
POST {{baseUrl}}/applications
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "userId": 1,
  "desiredRoleId": 2
}

### 2. Get all applications
GET {{baseUrl}}/applications
Authorization: Bearer {{auth_token}}

### 3. Get user application
GET {{baseUrl}}/applications/user/1
Authorization: Bearer {{auth_token}}

### 4. Approve application
PATCH {{baseUrl}}/applications/1/approve
Authorization: Bearer {{auth_token}}

### 5. Reject application  
PATCH {{baseUrl}}/applications/1/reject
Authorization: Bearer {{auth_token}}