### Users API Tests
@baseUrl = http://localhost:4000
@contentType = application/json
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoic3Rhc2FzdGVuZW5rbzAyQGdtYWlsLmNvbSIsImlhdCI6MTc1OTY3OTg5MSwiZXhwIjoxNzU5NjgzNDkxfQ.LFwdHwfLq-HJtGR2mDIyNNGZzw495LPtQXDt2TF41ts
### 1. Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{auth_token}}

### 2. Get user by ID  
GET {{baseUrl}}/users/1
Authorization: Bearer {{auth_token}}

### 3. Add worker
POST {{baseUrl}}/users/add-worker
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "name": "Петро",
  "surname": "Водій",
  "age": 30,
  "email": "driver@example.com",
  "password": "driver123",
  "role": "Водій"
}

### 4. Update user
PATCH {{baseUrl}}/users/8
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "role": "Водій"
}

### 5. Remove worker
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{auth_token}}